---
namespace: damex
name: plex
version: 1.1.1
readme: README.md
authors:
  - Roman Kuzmitskii <ansible@damex.org>
description: plex collection
license_file: LICENSE
tags:
  - application
  - linux
  - plex
repository: https://github.com/damex/ansible-collections-plex
dependencies:
  damex.apt: ">=1.4.6"
