---
argument_specs:
  main:
    options:
      plex_package_name:
        type: str
      plex_package_version:
        type: str
      plex_package_state:
        type: str
        choices:
          - absent
          - present
      plex_user:
        type: str
      plex_home:
        type: path
      plex_shell:
        type: path
      plex_user_state:
        type: str
        choices:
          - absent
          - present
      plex_group:
        type: str
      plex_group_state:
        type: str
        choices:
          - absent
          - present
      plex_user_extra_groups:
        type: list
        elements: str
      plex_service_name:
        type: str
      plex_apt_key_id:
        type: str
      plex_apt_key_url:
        type: str
      plex_apt_key_state:
        type: str
        choices:
          - absent
          - present
      plex_apt_repository_name:
        type: str
      plex_apt_repository_file:
        type: str
      plex_apt_repository_url:
        type: str
      plex_apt_repository_distribution:
        type: str
      plex_apt_repository_components:
        type: list
        elements: str
      plex_apt_repository_state:
        type: str
        choices:
          - absent
          - present
      plex_yum_repository_name:
        type: str
      plex_yum_repository_file:
        type: str
      plex_yum_repository_baseurl:
        type: str
      plex_yum_repository_gpgkey:
        type: str
      plex_yum_repository_state:
        type: str
        choices:
          - absent
          - present
