---
galaxy_info:
  role_name: plex
  author: Roman Kuzmitskii
  description: plex role
  license: GPLv2
  min_ansible_version: 2.10.6
  galaxy_tags:
    - plex
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
dependencies: []
