---
- name: Ensure plex apt key
  ansible.builtin.include_role:
    name: damex.apt.apt_keys
  vars:
    apt_keys: # noqa: var-naming[no-role-prefix]
      - id: "{{ plex_apt_key_id }}"
        url: "{{ plex_apt_key_url }}"
        state: "{{ plex_apt_key_state }}"
  when: ansible_facts['pkg_mgr'] == "apt"
