---
- name: check if i965_drv_video.so is exist
  stat:
    path: "{{ plex_dri_i965_so_file }}"
  register: plex_dri_i965_so

- name: ensure iHD_drv_video.so is absent
  file:
    path: "{{ plex_dri_ihd_so_file }}"
    state: "absent"
  when: plex_dri_i965_so.stat.exists
  become: true
  register: plex_dri_ihd_so
