---
- name: Ensure plex
  block:
    - name: Ensure plex group
      ansible.builtin.import_tasks: group.yml
    - name: Ensure plex user
      ansible.builtin.import_tasks: user.yml
    - name: Ensure plex key
      ansible.builtin.import_tasks: key.yml
    - name: Ensure plex repository
      ansible.builtin.import_tasks: repository.yml
    - name: Ensure plex package
      ansible.builtin.import_tasks: package.yml
  tags:
    - plex
