---
- name: Ensure plex
  tags:
    - plex
  block:
    - name: Ensure plex group
      ansible.builtin.import_tasks: group.yml
    - name: Ensure plex user
      ansible.builtin.import_tasks: user.yml
    - name: Ensure plex apt key
      ansible.builtin.import_tasks: apt_key.yml
    - name: Ensure plex apt repository
      ansible.builtin.import_tasks: apt_repository.yml
    - name: Ensure plex yum repository
      ansible.builtin.import_tasks: yum_repository.yml
    - name: Ensure plex package
      ansible.builtin.import_tasks: package.yml
    - name: Ensure plex systemd service
      ansible.builtin.import_tasks: systemd_service.yml
