---
- name: Ensure plex package
  ansible.builtin.include_role:
    name: damex.apt.apt_packages
  vars:
    apt_packages:
      - name: "{{ plex_package_name }}"
        version: "{{ plex_package_version }}"
        state: "{{ plex_package_state }}"
