---
- name: ensure plex user
  ansible.builtin.user:
    name: "{{ plex_user }}"
    state: "{{ plex_user_state }}"
    group: "{{ plex_group }}"
    groups: "{{ plex_user_extra_groups | join(', ') }}"
    home: "{{ plex_home }}"
    shell: "{{ plex_shell }}"
  become: true
