---
name: linting
on: # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install --user pipenv
      - run: pipenv install --deploy
      - run: pipenv run ansible-lint
