---
name: linting
on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  molecule-ubuntu-20.04:
    name: ansible-lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
